name: "test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      WP_PATH: /var/www/html
      PLUGIN_PATH: /var/www/html/wp-content/plugins/wpoven-performance-logs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP 8.0
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.0 php8.0-cli php8.0-fpm php8.0-mbstring php8.0-xml php8.0-mysql

      - name: Verify PHP Installation
        run: php -v

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Install WordPress
        run: |
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          sudo mv wordpress/* $WP_PATH
          sudo cp $WP_PATH/wp-config-sample.php $WP_PATH/wp-config.php
          sudo sed -i "s/database_name_here/wordpress_test/" $WP_PATH/wp-config.php
          sudo sed -i "s/username_here/root/" $WP_PATH/wp-config.php
          sudo sed -i "s/password_here/root/" $WP_PATH/wp-config.php
          mysql -u root --password=root -e "CREATE DATABASE wordpress_test"
          sudo chmod -R 755 $WP_PATH
          sudo service apache2 start

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Install WordPress
        run: |
          cd $WP_PATH
          wp core install --url="http://localhost" --title="Test Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com"

      - name: Clone the plugin repository
        run: |
          sudo mkdir -p $PLUGIN_PATH
          sudo git clone https://github.com/shyambaseapp/wpoven-performance-logs.git $PLUGIN_PATH
          cd $PLUGIN_PATH
          sudo git submodule update --init --recursive
          sudo chown -R www-data:www-data $PLUGIN_PATH

      - name: Activate the plugin
        run: |
          cd $WP_PATH
          wp plugin activate wpoven-performance-logs 

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with: 
          exclude-checks: 'i18n_usage'
          exclude-checks: 'late_escaping'
        env:
          PLUGIN_DIR: /var/www/html/wp-content/plugins/wpoven-performance-logs
          PLUGIN_SLUG: wpoven-performance-logs
          WP_VERSION: latest
