name: "test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP 8.0
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php8.0 php8.0-cli php8.0-fpm php8.0-mbstring php8.0-xml php8.0-mysql

      - name: Verify PHP Installation
        run: php -v

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Install WordPress
        run: |
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          sudo mv wordpress/* /var/www/html/
          sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          sudo sed -i "s/database_name_here/wordpress_test/" /var/www/html/wp-config.php
          sudo sed -i "s/username_here/root/" /var/www/html/wp-config.php
          sudo sed -i "s/password_here/root/" /var/www/html/wp-config.php
          mysql -u root --password=root -e "CREATE DATABASE wordpress_test"
          sudo chmod -R 755 /var/www/html
          sudo service apache2 start

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Install Wordpress
        run: |
          cd /var/www/html
          wp core install --url="http://localhost" --title="Test Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com"

      - name: Clone the plugin repository
        run: |
          sudo mkdir -p /var/www/html/wp-content/plugins/wpoven-performance-logs/
          sudo git clone https://github.com/shyambaseapp/wpoven-performance-logs.git /var/www/html/wp-content/plugins/wpoven-performance-logs/
          cd /var/www/html/wp-content/plugins/wpoven-performance-logs/
          pwd
          sudo git submodule update --init --recursive
          sudo chown -R www-data:www-data /var/www/html/wp-content/plugins/wpoven-performance-logs/


      - name: Activate the plugin
        run: |
          cd /var/www/html
          wp plugin activate wpoven-performance-logs 

        
      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        env:
          PLUGIN_DIR: /var/www/html/wp-content/plugins/wpoven-performance-logs
          PLUGIN_SLUG: wpoven-performance-logs
          WP_VERSION: null
        run: |
          find /var/www/html/wp-content/plugins/wpoven-performance-logs/ -type f ! -path "*/redux-framework/*" | xargs -n1 -I{} php -l {}
          find /var/www/html/wp-content/plugins/wpoven-performance-logs/ -type f ! -path "*/your-textdomain-here/*" | xargs -n1 -I{} php -l {}
